- name: Add certificates to system anchors dir
  copy:
    dest: "{{ source }}/{{ cert.alias }}.pem"
    content: "{{ cert.pem }}"
  register: ca_certificates_add_result

- name:
  set_fact:
    _ca_certificates_needs_rebuild: >-
      ca_certificates_add_result is changed
      or _ca_certificates_needs_rebuild | default(False)
