- name: Add certificates to system anchors dir
  copy:
    dest: "{{ source }}/{{ cert.alias }}.pem"
    content: "{{ cert.pem }}"
    mode: '0600'
  register: ca_certificates_add_result
  notify: rebuild certificates
