---
# Role tasks

- name: Setup certificates
  vars:
    ca_certificates_managed: >-
      {{ (ca_certificates_load_from_hostvars
          and not ca_certificates_hostvars_certs is string)
          | ternary([ ca_certificates_hostvars_certs ] | flatten
                    + ca_certificates,
                    ca_certificates) }}
    source: >-
      {{ (cert.priority | default("low") == "high")
         | ternary(ca_certificates_high_priority_anchors_dir,
                   ca_certificates_low_priority_anchors_dir) }}
  block:
    - name: Add certificates to system anchors dir
      loop: >-
        {{ ca_certificates_managed
           | selectattr("state", "equalto", "present")
           | list }}
      loop_control:
        loop_var: cert
        label: "{{ cert.alias }}"
      copy:
        dest: "{{ source }}/{{ cert.alias }}.pem"
        content: "{{ cert.pem }}"
      register: ca_certificates_add_result

    - name: Remove certificates from system anchors dir
      loop: >-
        {{ ca_certificates_managed
           | selectattr("state", "equalto", "absent")
           | list }}
      loop_control:
        loop_var: cert
        label: "{{ cert.alias }}"
      file:
        path: "{{ source }}/{{ cert.alias }}.pem"
        state: absent
      register: ca_certificates_remove_result

    - name: Rebuild the certificates trust database
      when:
        (ca_certificates_add_result.results
         + ca_certificates_remove_result.results)
        | select("changed")
        | list
        | length > 0
      command: "update-ca-trust extract"
  tags:
    - role::ca_certificates
