---
# Role tasks

- name: Setup certificates
  vars:
    ca_certificates_managed: >-
      {{ (ca_certificates_load_from_hostvars
          and not ca_certificates_hostvars_certs is string)
          | ternary([ ca_certificates_hostvars_certs ] | flatten
                    + ca_certificates,
                    ca_certificates) }}
    source: >-
      {{ (cert.priority | default("low") == "high")
         | ternary(ca_certificates_high_priority_anchors_dir,
                   ca_certificates_low_priority_anchors_dir) }}
  block:
    - name: Add certificates to system anchors dir
      loop: >-
        {{ ca_certificates_managed
           | selectattr("state", "equalto", "present")
           | list }}
      loop_control:
        loop_var: cert
        label: "{{ cert.alias }}"
      include_tasks: add_certificate.yml

    - name: Remove certificates from system anchors dir
      loop: >-
        {{ ca_certificates_managed
           | selectattr("state", "equalto", "absent")
           | list }}
      loop_control:
        loop_var: cert
        label: "{{ cert.alias }}"
      file:
        path: "{{ source }}/{{ cert.alias }}.pem"
        state: absent
      register: ca_certificates_remove_result

    - name: Rebuild the certificates trust database
      when:
        _ca_certificates_needs_rebuild | default(False)
        or ca_certificates_remove_result.results
        | select("changed")
        | list
        | length > 0
      command: "update-ca-trust extract"

    - name: Clean internal fact values
      vars:
        ca_certificates_internal_facts:
          - _ca_certificates_needs_rebuild
      include_tasks: clean_facts.yml

  tags:
    - role::ca_certificates
