---
# Role tasks

- name: Setup certificates
  vars:
    ca_certificates_managed: >-
      {{ (ca_certificates_load_from_hostvars
          and not ca_certificates_hostvars_certs is string)
          | ternary([ ca_certificates_hostvars_certs ] | flatten
                    + ca_certificates,
                    ca_certificates) }}
    source: >-
      {{ (cert.priority | default("low") == "high")
         | ternary(ca_certificates_high_priority_anchors_dir,
                   ca_certificates_low_priority_anchors_dir) }}
  block:
    - name: Add certificates to system anchors dir
      loop: >-
        {{ ca_certificates_managed
           | selectattr("state", "equalto", "present")
           | list }}
      loop_control:
        loop_var: cert
        label: "{{ cert.alias }}"
      include_tasks: add_certificate.yml

    - name: Remove certificates from system anchors dir
      loop: >-
        {{ ca_certificates_managed
           | selectattr("state", "equalto", "absent")
           | list }}
      loop_control:
        loop_var: cert
        label: "{{ cert.alias }}"
      file:
        path: "{{ source }}/{{ cert.alias }}.pem"
        state: absent
      notify: rebuild certificates

  tags:
    - role::ca_certificates
