---

- name: Converge
  hosts: molecule_hosts
  gather_facts: no
  roles:
    - amtega.ca_certificates
  vars:
    ca_certificates:
      - alias: mozilla
        description: Mozilla
        state: absent
        priority: high

      - alias: debian
        description: Debian
        state: absent
        priority: low
