---

dependency:
  name: galaxy
  enabled: yes
  options:
    ignore-certs: yes
    ignore-errors: yes
    role-file: >-
      ${MOLECULE_SCENARIO_DIRECTORY}/../resources/requirements.yml
    requirements-file: >-
      ${MOLECULE_SCENARIO_DIRECTORY}/../resources/requirements.yml
driver:
  name: podman
lint: "${MOLECULE_SCENARIO_DIRECTORY}/../resources/linters.sh"
platforms:
  - name: "http-server-${INSTANCE_UUID:-1}"
    image: quay.io/centos/centos:stream8
    exposed_ports: ["8000"]
    network: bridge
    groups:
      - molecule_prepare_hosts
  - name: "centos7-${INSTANCE_UUID:-1}"
    image: quay.io/centos/centos:centos7
    network: bridge
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_7
  - name: "centos8-${INSTANCE_UUID:-1}"
    image: quay.io/centos/centos:stream8
    network: bridge
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_8
  - name: "fedora34-${INSTANCE_UUID:-1}"
    image: quay.io/fedora/fedora:34
    network: bridge
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
      - molecule_hosts_fedora_34
  - name: "fedora35-${INSTANCE_UUID:-1}"
    image: quay.io/fedora/fedora:35
    network: bridge
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
      - molecule_hosts_fedora_35
provisioner:
  name: ansible
  playbooks:
    cleanup: ../resources/cleanup.yml
    side_effect: ../resources/side_effect.yml
  config_options:
    defaults:
      callbacks_enabled: profile_tasks
      action_plugins: $PWD/action_plugins
  inventory:
    hosts:
      all:
        vars:
          certificates_host: "{{ groups['molecule_prepare_hosts'] | first }}"
          certificates_host_ip: >-
            {{ hostvars[certificates_host].ansible_default_ipv4.address }}
          ca_certificates_artifact_defaults:
            no_log: no
          ca_certificates:
            - description: Mozilla
              # this test needs alias to be extracted from
              #   `openssl x509 -inform PEM -noout -alias`
              # for verification to work
              alias: mozilla.org
              state: present
              priority: high
              artifact:
                type: http
                host: http://{{ certificates_host_ip }}:8000
                path: /
                file: mozilla.org.pem

            - alias: www.debian.org
              description: Debian
              state: present
              priority: low
              artifact:
                type: http
                host: http://{{ certificates_host_ip }}:8000
                path: /
                file: www.debian.org.pem
      molecule_hosts_fedora:
        vars:
          ansible_python_interpreter: /usr/bin/python3
verifier:
  name: ansible
