---

dependency:
  name: galaxy
driver:
  name: docker
lint: "${MOLECULE_SCENARIO_DIRECTORY}/../resources/linters.sh"
platforms:
  - name: "centos7-${INSTANCE_UUID:-1}"
    image: centos:7
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_7
  - name: "centos8-${INSTANCE_UUID:-1}"
    image: centos:8
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_8
  - name: "fedora33-${INSTANCE_UUID:-1}"
    image: fedora:33
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
      - molecule_hosts_fedora_33
  - name: "fedora34-${INSTANCE_UUID:-1}"
    image: fedora:34
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
      - molecule_hosts_fedora_34
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      action_plugins: $PWD/action_plugins
  inventory:
    hosts:
      molecule_hosts:
        vars:
          ca_certificates_artifact_defaults:
            no_log: no
          ca_certificates:
            - description: Mozilla
              # this test needs alias to be extracted from
              #   `openssl x509 -inform PEM -noout -alias`
              # for verification to work
              alias: mozilla.org
              state: present
              priority: high
              artifact:
                type: https
                host: https://cacerts.digicert.com
                path: /
                file: RapidSSLTLSDVRSAMixedSHA2562020CA-1.crt.pem

            - alias: www.debian.org
              description: Debian
              state: present
              priority: low
              artifact:
                type: https
                host: https://cacerts.digicert.com
                path: /
                file: DigiCertGlobalRootCA.crt.pem
      molecule_hosts_fedora:
        vars:
          ansible_python_interpreter: /usr/bin/python3
verifier:
  name: ansible
