---

dependency:
  name: galaxy
  enabled: yes
  options:
    ignore-certs: yes
    ignore-errors: yes
    role-file: >-
      ${MOLECULE_SCENARIO_DIRECTORY}/../resources/requirements.yml
    requirements-file: >-
      ${MOLECULE_SCENARIO_DIRECTORY}/../resources/requirements.yml
driver:
  name: docker
lint: "${MOLECULE_SCENARIO_DIRECTORY}/../resources/linters.sh"
platforms:
  - name: "http-server-${INSTANCE_UUID:-1}"
    image: centos:8
    exposed_ports: ['8000']
    groups:
      - molecule_prepare_hosts
  - name: "centos7-${INSTANCE_UUID:-1}"
    image: centos:7
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_7
  - name: "centos8-${INSTANCE_UUID:-1}"
    image: centos:8
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_8
  - name: "fedora33-${INSTANCE_UUID:-1}"
    image: fedora:33
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
      - molecule_hosts_fedora_33
  - name: "fedora34-${INSTANCE_UUID:-1}"
    image: fedora:34
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
      - molecule_hosts_fedora_34
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      action_plugins: $PWD/action_plugins
  inventory:
    hosts:
      all:
        vars:
          certificates_host: "{{ groups['molecule_prepare_hosts'] | first }}"
          certificates_host_ip: >-
            {{ hostvars[certificates_host].ansible_default_ipv4.address }}
          ca_certificates_artifact_defaults:
            no_log: no
          ca_certificates:
            - description: Mozilla
              # this test needs alias to be extracted from
              #   `openssl x509 -inform PEM -noout -alias`
              # for verification to work
              alias: mozilla.org
              state: present
              priority: high
              artifact:
                type: http
                host: http://{{ certificates_host_ip }}:8000
                path: /
                file: mozilla.org.pem

            - alias: www.debian.org
              description: Debian
              state: present
              priority: low
              artifact:
                type: http
                host: http://{{ certificates_host_ip }}:8000
                path: /
                file: www.debian.org.pem
      molecule_hosts_fedora:
        vars:
          ansible_python_interpreter: /usr/bin/python3
verifier:
  name: ansible
